version: "3"

services:
  api:
    build: api
    ports:
      - "3001:3001"
    depends_on:
      - db
  db:
    build: db
    ports:
      - "6379:6379"
    volumes:
      - db_data:./data

  redis-exporter:
    image: oliver006/redis_exporter
    ports:
      - "9121:9121"
    command:
      [
        "--redis.addr=redis://db:6379",
        "--redis.password=",
        "--web.listen-address=:9121",
        "--web.telemetry-path=/metrics",
      ]
    depends_on:
      - db

  prometheus:
    image: prom/prometheus:v2.45.3
    container_name: prometheus
    hostname: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - "9090:9090"
    
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    hostname: grafana
    restart: unless-stopped
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin # Change this
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

volumes:
  prometheus_data:
  grafana_data:
  db_data:
